#spring:
#  datasource:
#    url: jdbc:h2:file:./data/passkeydb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#
#  h2:
#    console:
#      enabled: true
#
#
#server:
#  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://ep-lively-hat-axxynppi-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
#    username: neondb_owner
#    password: npg_brt58EDRCwqI
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true